{% set name = "mintimegrad" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  script: python -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}

  host:
    - python
    - pip
    - pybind11 >=2.6.0

  run:
    - numpy
    - python

test:
  imports:
    - mintimegrad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kejang/mintimegrad
  summary: Python Wrapper of Miki Lustig's tOptGrad
  license: LGPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kejang
