{% set name = "mintimegrad" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - pip
    - pybind11
    - python
  run:
    - numpy >=1.17.3
    - pybind11 >=2.6.0
    - python

test:
  imports:
    - mintimegrad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kejang/mintimegrad
  summary: Python Wrapper of Miki Lustig's tOptGrad
  license: LGPL-3.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - kejang
